### ISSUE TITLE
Failed to startup encoder

### ISSUE THREAD

**Issue by bobMuk** [xbelanch/OBS4Pi#1]
Everything compiles without an issue, running on Pi 4 with 4GB and /etc/debian_version says 10.7

Just want to do some recording.... start up by running:
`
MESA_GL_VERSION_OVERRIDE=3.3 obs
`

The configuration wizard says "Failed to startup encoder"
...and on the command line I'm seeing this output from OBS:

`
==== Auto-config wizard testing commencing ======

info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1920x1080
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          709/Partial
info: NV12 texture support not available
info: ---------------------------------
info: [x264 encoder: 'test_x264'] preset: veryfast
info: [x264 encoder: 'test_x264'] profile: high
info: [x264 encoder: 'test_x264'] settings:
	rate_control: CRF
	bitrate:      0
	buffer size:  0
	crf:          20
	fps_num:      30
	fps_den:      1
	width:        1920
	height:       1080
	keyint:       250

x264 [error]: high profile doesn't support lossless
warning: [x264 encoder: 'test_x264'] Failed to set x264 profile 'high'
info: [x264 encoder: 'test_x264'] invalid crop-rect 0,0,0,4294967295

warning: [x264 encoder: 'test_x264'] x264 failed to load
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1280x720
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          709/Partial
info: NV12 texture support not available
`

Also seeing the same output logged if I try and start a recording, dialog box says "Starting the output failed, please check the log for details."

**Comment by xbelanch** [comment]
Can you select h264_omx as video encoder at recording advanced options from the Output configuration? Can you please share a screeshot?
