### ISSUE TITLE
Building FFMPEG step fails

### ISSUE THREAD

**Issue by Hubert97** [xbelanch/OBS4Pi#10]
Probably too new version?

STD Out:
-----------------------------------
Get and build FFMPEG
-----------------------------------
Cloning into '/tmp/tmp.ReOuIZ4y3V/FFmpeg'...
remote: Enumerating objects: 7277, done.
remote: Counting objects: 100% (7277/7277), done.
remote: Compressing objects: 100% (5578/5578), done.
remote: Total 7277 (delta 1924), reused 3516 (delta 1407), pack-reused 0
Receiving objects: 100% (7277/7277), 15.37 MiB | 9.14 MiB/s, done.
Resolving deltas: 100% (1924/1924), done.
Note: checking out 'f719f869907764e6412a6af6e178c46e5f915d25'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Checking out files: 100% (7327/7327), done.
install prefix            /usr/local
source path               .
C compiler                gcc
C library                 glibc
ARCH                      arm (armv8-a)
big-endian                no
runtime cpu detection     yes
ARMv5TE enabled           yes
ARMv6 enabled             yes
ARMv6T2 enabled           yes
VFP enabled               yes
NEON enabled              yes
THUMB enabled             no
debug symbols             yes
strip symbols             yes
optimize for size         no
optimizations             yes
static                    yes
shared                    yes
postprocessing support    yes
network support           yes
threading support         pthreads
safe bitstream reader     yes
texi2html enabled         no
perl enabled              yes
pod2man enabled           yes
makeinfo enabled          yes
makeinfo supports HTML    yes

External libraries:
alsa                    libmp3lame              libvorbis               libxml2
iconv                   libopencore_amrnb       libvpx                  libzimg
libaom                  libopencore_amrwb       libwebp                 openssl
libass                  libopus                 libx264                 sdl2
libdav1d                librtmp                 libx265                 sndio
libdrm                  libsnappy               libxcb                  xlib
libfdk_aac              libsoxr                 libxcb_shape            zlib
libfreetype             libssh                  libxcb_shm
libkvazaar              libv4l2                 libxcb_xfixes

External libraries providing hardware acceleration:
mmal                    v4l2_m2m                vdpau
omx                     vaapi

Libraries:
avcodec                 avfilter                avutil                  swresample
avdevice                avformat                postproc                swscale

Programs:
ffmpeg                  ffplay                  ffprobe

Enabled decoders:
aac                     dnxhd                   mp1float                s302m
aac_fixed               dolby_e                 mp2                     sami
aac_latm                dpx                     mp2float                sanm
aasc                    dsd_lsbf                mp3                     sbc
ac3                     dsd_lsbf_planar         mp3adu                  scpr
ac3_fixed               dsd_msbf                mp3adufloat             screenpresso
acelp_kelvin            dsd_msbf_planar         mp3float                sdx2_dpcm
adpcm_4xm               dsicinaudio             mp3on4                  sgi
adpcm_adx               dsicinvideo             mp3on4float             sgirle
adpcm_afc               dss_sp                  mpc7                    sheervideo
adpcm_agm               dst                     mpc8                    shorten
adpcm_aica              dvaudio                 mpeg1_v4l2m2m           sipr
adpcm_argo              dvbsub                  mpeg1video              siren
adpcm_ct                dvdsub                  mpeg2_mmal              smackaud
adpcm_dtk               dvvideo                 mpeg2_v4l2m2m           smacker
adpcm_ea                dxa                     mpeg2video              smc
adpcm_ea_maxis_xa       dxtory                  mpeg4                   smvjpeg
adpcm_ea_r1             dxv                     mpeg4_mmal              snow
adpcm_ea_r2             eac3                    mpeg4_v4l2m2m           sol_dpcm
adpcm_ea_r3             eacmv                   mpegvideo               sonic
adpcm_ea_xas            eamad                   mpl2                    sp5x
adpcm_g722              eatgq                   msa1                    speedhq
adpcm_g726              eatgv                   mscc                    srgc
adpcm_g726le            eatqi                   msmpeg4v1               srt
adpcm_ima_alp           eightbps                msmpeg4v2               ssa
adpcm_ima_amv           eightsvx_exp            msmpeg4v3               stl
adpcm_ima_apc           eightsvx_fib            msrle                   subrip
adpcm_ima_apm           escape124               mss1                    subviewer
adpcm_ima_cunning       escape130               mss2                    subviewer1
adpcm_ima_dat4          evrc                    msvideo1                sunrast
adpcm_ima_dk3           exr                     mszh                    svq1
adpcm_ima_dk4           ffv1                    mts2                    svq3
adpcm_ima_ea_eacs       ffvhuff                 mv30                    tak
adpcm_ima_ea_sead       ffwavesynth             mvc1                    targa
adpcm_ima_iss           fic                     mvc2                    targa_y216
adpcm_ima_mtf           fits                    mvdv                    tdsc
adpcm_ima_oki           flac                    mvha                    text
adpcm_ima_qt            flashsv                 mwsc                    theora
adpcm_ima_rad           flashsv2                mxpeg                   thp
adpcm_ima_smjpeg        flic                    nellymoser              tiertexseqvideo
adpcm_ima_ssi           flv                     notchlc                 tiff
adpcm_ima_wav           fmvc                    nuv                     tmv
adpcm_ima_ws            fourxm                  on2avc                  truehd
adpcm_ms                fraps                   opus                    truemotion1
adpcm_mtaf              frwu                    paf_audio               truemotion2
adpcm_psx               g2m                     paf_video               truemotion2rt
adpcm_sbpro_2           g723_1                  pam                     truespeech
adpcm_sbpro_3           g729                    pbm                     tscc
adpcm_sbpro_4           gdv                     pcm_alaw                tscc2
adpcm_swf               gif                     pcm_bluray              tta
adpcm_thp               gremlin_dpcm            pcm_dvd                 twinvq
adpcm_thp_le            gsm                     pcm_f16le               txd
adpcm_vima              gsm_ms                  pcm_f24le               ulti
adpcm_xa                h261                    pcm_f32be               utvideo
adpcm_yamaha            h263                    pcm_f32le               v210
adpcm_zork              h263_v4l2m2m            pcm_f64be               v210x
agm                     h263i                   pcm_f64le               v308
aic                     h263p                   pcm_lxf                 v408
alac                    h264                    pcm_mulaw               v410
alias_pix               h264_mmal               pcm_s16be               vb
als                     h264_v4l2m2m            pcm_s16be_planar        vble
amrnb                   hap                     pcm_s16le               vc1
amrwb                   hca                     pcm_s16le_planar        vc1_mmal
amv                     hcom                    pcm_s24be               vc1_v4l2m2m
anm                     hevc                    pcm_s24daud             vc1image
ansi                    hevc_v4l2m2m            pcm_s24le               vcr1
ape                     hnm4_video              pcm_s24le_planar        vmdaudio
apng                    hq_hqa                  pcm_s32be               vmdvideo
aptx                    hqx                     pcm_s32le               vmnc
aptx_hd                 huffyuv                 pcm_s32le_planar        vorbis
arbc                    hymt                    pcm_s64be               vp3
ass                     iac                     pcm_s64le               vp4
asv1                    idcin                   pcm_s8                  vp5
asv2                    idf                     pcm_s8_planar           vp6
atrac1                  iff_ilbm                pcm_u16be               vp6a
atrac3                  ilbc                    pcm_u16le               vp6f
atrac3al                imc                     pcm_u24be               vp7
atrac3p                 imm4                    pcm_u24le               vp8
atrac3pal               imm5                    pcm_u32be               vp8_v4l2m2m
atrac9                  indeo2                  pcm_u32le               vp9
aura                    indeo3                  pcm_u8                  vp9_v4l2m2m
aura2                   indeo4                  pcm_vidc                vplayer
avrn                    indeo5                  pcx                     vqa
avrp                    interplay_acm           pfm                     wavpack
avs                     interplay_dpcm          pgm                     wcmv
avui                    interplay_video         pgmyuv                  webp
ayuv                    jacosub                 pgssub                  webvtt
bethsoftvid             jpeg2000                pictor                  wmalossless
bfi                     jpegls                  pixlet                  wmapro
bink                    jv                      pjs                     wmav1
binkaudio_dct           kgv1                    png                     wmav2
binkaudio_rdft          kmvc                    ppm                     wmavoice
bintext                 lagarith                prores                  wmv1
bitpacked               libaom_av1              prosumer                wmv2
bmp                     libdav1d                psd                     wmv3
bmv_audio               libfdk_aac              ptx                     wmv3image
bmv_video               libopencore_amrnb       qcelp                   wnv1
brender_pix             libopencore_amrwb       qdm2                    wrapped_avframe
c93                     libopus                 qdmc                    ws_snd1
cavs                    libvorbis               qdraw                   xan_dpcm
ccaption                libvpx_vp8              qpeg                    xan_wc3
cdgraphics              libvpx_vp9              qtrle                   xan_wc4
cdtoons                 loco                    r10k                    xbin
cdxl                    lscr                    r210                    xbm
cfhd                    m101                    ra_144                  xface
cinepak                 mace3                   ra_288                  xl
clearvideo              mace6                   ralf                    xma1
cljr                    magicyuv                rasc                    xma2
cllc                    mdec                    rawvideo                xpm
comfortnoise            metasound               realtext                xsub
cook                    microdvd                rl2                     xwd
cpia                    mimic                   roq                     y41p
cscd                    mjpeg                   roq_dpcm                ylc
cyuv                    mjpegb                  rpza                    yop
dca                     mlp                     rscc                    yuv4
dds                     mmvideo                 rv10                    zero12v
derf_dpcm               motionpixels            rv20                    zerocodec
dfa                     movtext                 rv30                    zlib
dirac                   mp1                     rv40                    zmbv

Enabled encoders:
a64multi                gif                     opus                    roq
a64multi5               h261                    pam                     roq_dpcm
aac                     h263                    pbm                     rv10
ac3                     h263_v4l2m2m            pcm_alaw                rv20
ac3_fixed               h263p                   pcm_dvd                 s302m
adpcm_adx               h264_omx                pcm_f32be               sbc
adpcm_g722              h264_v4l2m2m            pcm_f32le               sgi
adpcm_g726              h264_vaapi              pcm_f64be               snow
adpcm_g726le            hap                     pcm_f64le               sonic
adpcm_ima_qt            hevc_v4l2m2m            pcm_mulaw               sonic_ls
adpcm_ima_ssi           hevc_vaapi              pcm_s16be               srt
adpcm_ima_wav           huffyuv                 pcm_s16be_planar        ssa
adpcm_ms                jpeg2000                pcm_s16le               subrip
adpcm_swf               jpegls                  pcm_s16le_planar        sunrast
adpcm_yamaha            libaom_av1              pcm_s24be               svq1
alac                    libfdk_aac              pcm_s24daud             targa
alias_pix               libkvazaar              pcm_s24le               text
amv                     libmp3lame              pcm_s24le_planar        tiff
apng                    libopencore_amrnb       pcm_s32be               truehd
aptx                    libopus                 pcm_s32le               tta
aptx_hd                 libvorbis               pcm_s32le_planar        utvideo
ass                     libvpx_vp8              pcm_s64be               v210
asv1                    libvpx_vp9              pcm_s64le               v308
asv2                    libwebp                 pcm_s8                  v408
avrp                    libwebp_anim            pcm_s8_planar           v410
avui                    libx264                 pcm_u16be               vc2
ayuv                    libx264rgb              pcm_u16le               vorbis
bmp                     libx265                 pcm_u24be               vp8_v4l2m2m
cinepak                 ljpeg                   pcm_u24le               vp8_vaapi
cljr                    magicyuv                pcm_u32be               vp9_vaapi
comfortnoise            mjpeg                   pcm_u32le               wavpack
dca                     mjpeg_vaapi             pcm_u8                  webvtt
dnxhd                   mlp                     pcm_vidc                wmav1
dpx                     movtext                 pcx                     wmav2
dvbsub                  mp2                     pgm                     wmv1
dvdsub                  mp2fixed                pgmyuv                  wmv2
dvvideo                 mpeg1video              png                     wrapped_avframe
eac3                    mpeg2_vaapi             ppm                     xbm
ffv1                    mpeg2video              prores                  xface
ffvhuff                 mpeg4                   prores_aw               xsub
fits                    mpeg4_omx               prores_ks               xwd
flac                    mpeg4_v4l2m2m           qtrle                   y41p
flashsv                 msmpeg4v2               r10k                    yuv4
flashsv2                msmpeg4v3               r210                    zlib
flv                     msvideo1                ra_144                  zmbv
g723_1                  nellymoser              rawvideo

Enabled hwaccels:
h263_vaapi              mjpeg_vaapi             mpeg4_vdpau             wmv3_vaapi
h264_vaapi              mpeg1_vdpau             vc1_vaapi               wmv3_vdpau
h264_vdpau              mpeg2_vaapi             vc1_vdpau
hevc_vaapi              mpeg2_vdpau             vp8_vaapi
hevc_vdpau              mpeg4_vaapi             vp9_vaapi

Enabled parsers:
aac                     dpx                     h264                    rv40
aac_latm                dvaudio                 hevc                    sbc
ac3                     dvbsub                  jpeg2000                sipr
adx                     dvd_nav                 mjpeg                   tak
av1                     dvdsub                  mlp                     vc1
avs2                    flac                    mpeg4video              vorbis
bmp                     g723_1                  mpegaudio               vp3
cavsvideo               g729                    mpegvideo               vp8
cook                    gif                     opus                    vp9
dca                     gsm                     png                     webp
dirac                   h261                    pnm                     xma
dnxhd                   h263                    rv30

Enabled demuxers:
aa                      filmstrip               lvf                     rso
aac                     fits                    lxf                     rtp
ac3                     flac                    m4v                     rtsp
acm                     flic                    matroska                s337m
act                     flv                     mgsts                   sami
adf                     fourxm                  microdvd                sap
adp                     frm                     mjpeg                   sbc
ads                     fsb                     mjpeg_2000              sbg
adx                     fwse                    mlp                     scc
aea                     g722                    mlv                     sdp
afc                     g723_1                  mm                      sdr2
aiff                    g726                    mmf                     sds
aix                     g726le                  mov                     sdx
alp                     g729                    mp3                     segafilm
amr                     gdv                     mpc                     ser
amrnb                   genh                    mpc8                    shorten
amrwb                   gif                     mpegps                  siff
anm                     gsm                     mpegts                  sln
apc                     gxf                     mpegtsraw               smacker
ape                     h261                    mpegvideo               smjpeg
apm                     h263                    mpjpeg                  smush
apng                    h264                    mpl2                    sol
aptx                    hca                     mpsub                   sox
aptx_hd                 hcom                    msf                     spdif
aqtitle                 hevc                    msnwc_tcp               srt
argo_asf                hls                     mtaf                    stl
asf                     hnm                     mtv                     str
asf_o                   ico                     musx                    subviewer
ass                     idcin                   mv                      subviewer1
ast                     idf                     mvi                     sup
au                      iff                     mxf                     svag
av1                     ifv                     mxg                     swf
avi                     ilbc                    nc                      tak
avr                     image2                  nistsphere              tedcaptions
avs                     image2_alias_pix        nsp                     thp
avs2                    image2_brender_pix      nsv                     threedostr
bethsoftvid             image2pipe              nut                     tiertexseq
bfi                     image_bmp_pipe          nuv                     tmv
bfstm                   image_dds_pipe          ogg                     truehd
bink                    image_dpx_pipe          oma                     tta
bintext                 image_exr_pipe          paf                     tty
bit                     image_gif_pipe          pcm_alaw                txd
bmv                     image_j2k_pipe          pcm_f32be               ty
boa                     image_jpeg_pipe         pcm_f32le               v210
brstm                   image_jpegls_pipe       pcm_f64be               v210x
c93                     image_pam_pipe          pcm_f64le               vag
caf                     image_pbm_pipe          pcm_mulaw               vc1
cavsvideo               image_pcx_pipe          pcm_s16be               vc1t
cdg                     image_pgm_pipe          pcm_s16le               vividas
cdxl                    image_pgmyuv_pipe       pcm_s24be               vivo
cine                    image_pictor_pipe       pcm_s24le               vmd
codec2                  image_png_pipe          pcm_s32be               vobsub
codec2raw               image_ppm_pipe          pcm_s32le               voc
concat                  image_psd_pipe          pcm_s8                  vpk
dash                    image_qdraw_pipe        pcm_u16be               vplayer
data                    image_sgi_pipe          pcm_u16le               vqf
daud                    image_sunrast_pipe      pcm_u24be               w64
dcstr                   image_svg_pipe          pcm_u24le               wav
derf                    image_tiff_pipe         pcm_u32be               wc3
dfa                     image_webp_pipe         pcm_u32le               webm_dash_manifest
dhav                    image_xpm_pipe          pcm_u8                  webvtt
dirac                   image_xwd_pipe          pcm_vidc                wsaud
dnxhd                   ingenient               pjs                     wsd
dsf                     ipmovie                 pmp                     wsvqa
dsicin                  ircam                   pp_bnk                  wtv
dss                     iss                     pva                     wv
dts                     iv8                     pvf                     wve
dtshd                   ivf                     qcp                     xa
dv                      ivr                     r3d                     xbin
dvbsub                  jacosub                 rawvideo                xmv
dvbtxt                  jv                      realtext                xvag
dxa                     kux                     redspark                xwma
ea                      kvag                    rl2                     yop
ea_cdata                live_flv                rm                      yuv4mpegpipe
eac3                    lmlm4                   roq
epaf                    loas                    rpl
ffmetadata              lrc                     rsd

Enabled muxers:
a64                     framemd5                mpeg1vcd                rm
ac3                     g722                    mpeg1video              roq
adts                    g723_1                  mpeg2dvd                rso
adx                     g726                    mpeg2svcd               rtp
aiff                    g726le                  mpeg2video              rtp_mpegts
amr                     gif                     mpeg2vob                rtsp
apng                    gsm                     mpegts                  sap
aptx                    gxf                     mpjpeg                  sbc
aptx_hd                 h261                    mxf                     scc
asf                     h263                    mxf_d10                 segafilm
asf_stream              h264                    mxf_opatom              segment
ass                     hash                    null                    singlejpeg
ast                     hds                     nut                     smjpeg
au                      hevc                    oga                     smoothstreaming
avi                     hls                     ogg                     sox
avm2                    ico                     ogv                     spdif
avs2                    ilbc                    oma                     spx
bit                     image2                  opus                    srt
caf                     image2pipe              pcm_alaw                stream_segment
cavsvideo               ipod                    pcm_f32be               streamhash
codec2                  ircam                   pcm_f32le               sup
codec2raw               ismv                    pcm_f64be               swf
crc                     ivf                     pcm_f64le               tee
dash                    jacosub                 pcm_mulaw               tg2
data                    kvag                    pcm_s16be               tgp
daud                    latm                    pcm_s16le               truehd
dirac                   lrc                     pcm_s24be               tta
dnxhd                   m4v                     pcm_s24le               uncodedframecrc
dts                     matroska                pcm_s32be               vc1
dv                      matroska_audio          pcm_s32le               vc1t
eac3                    md5                     pcm_s8                  voc
f4v                     microdvd                pcm_u16be               w64
ffmetadata              mjpeg                   pcm_u16le               wav
fifo                    mkvtimestamp_v2         pcm_u24be               webm
fifo_test               mlp                     pcm_u24le               webm_chunk
filmstrip               mmf                     pcm_u32be               webm_dash_manifest
fits                    mov                     pcm_u32le               webp
flac                    mp2                     pcm_u8                  webvtt
flv                     mp3                     pcm_vidc                wtv
framecrc                mp4                     psp                     wv
framehash               mpeg1system             rawvideo                yuv4mpegpipe

Enabled protocols:
async                   http                    libssh                  tcp
cache                   httpproxy               md5                     tee
concat                  https                   mmsh                    tls
crypto                  icecast                 mmst                    udp
data                    librtmp                 pipe                    udplite
file                    librtmpe                prompeg                 unix
ftp                     librtmps                rtp
gopher                  librtmpt                srtp
hls                     librtmpte               subfile

Enabled filters:
abench                  chromashift             hqdn3d                  select
abitscope               ciescope                hqx                     selectivecolor
acompressor             codecview               hstack                  sendcmd
acontrast               color                   hue                     separatefields
acopy                   colorbalance            hwdownload              setdar
acrossfade              colorchannelmixer       hwmap                   setfield
acrossover              colorhold               hwupload                setparams
acrusher                colorkey                hysteresis              setpts
acue                    colorlevels             idet                    setrange
addroi                  colormatrix             il                      setsar
adeclick                colorspace              inflate                 settb
adeclip                 compand                 interlace               sharpness_vaapi
adelay                  compensationdelay       interleave              showcqt
aderivative             concat                  join                    showfreqs
adrawgraph              convolution             kerndeint               showinfo
aecho                   convolve                lagfun                  showpalette
aemphasis               copy                    lenscorrection          showspatial
aeval                   cover_rect              life                    showspectrum
aevalsrc                crop                    limiter                 showspectrumpic
afade                   cropdetect              loop                    showvolume
afftdn                  crossfeed               loudnorm                showwaves
afftfilt                crystalizer             lowpass                 showwavespic
afifo                   cue                     lowshelf                shuffleframes
afir                    curves                  lumakey                 shuffleplanes
afirsrc                 datascope               lut                     sidechaincompress
aformat                 dblur                   lut1d                   sidechaingate
agate                   dcshift                 lut2                    sidedata
agraphmonitor           dctdnoiz                lut3d                   sierpinski
ahistogram              deband                  lutrgb                  signalstats
aiir                    deblock                 lutyuv                  signature
aintegral               decimate                mandelbrot              silencedetect
ainterleave             deconvolve              maskedclamp             silenceremove
alimiter                dedot                   maskedmax               sinc
allpass                 deesser                 maskedmerge             sine
allrgb                  deflate                 maskedmin               smartblur
allyuv                  deflicker               maskedthreshold         smptebars
aloop                   deinterlace_vaapi       maskfun                 smptehdbars
alphaextract            dejudder                mcdeint                 sobel
alphamerge              delogo                  mcompand                spectrumsynth
amerge                  denoise_vaapi           median                  split
ametadata               derain                  mergeplanes             spp
amix                    deshake                 mestimate               sr
amovie                  despill                 metadata                ssim
amplify                 detelecine              midequalizer            stereo3d
amultiply               dilation                minterpolate            stereotools
anequalizer             displace                mix                     stereowiden
anlmdn                  dnn_processing          movie                   streamselect
anlms                   doubleweave             mpdecimate              subtitles
anoisesrc               drawbox                 mptestsrc               super2xsai
anull                   drawgraph               negate                  superequalizer
anullsink               drawgrid                nlmeans                 surround
anullsrc                drawtext                nnedi                   swaprect
apad                    drmeter                 noformat                swapuv
aperms                  dynaudnorm              noise                   tblend
aphasemeter             earwax                  normalize               telecine
aphaser                 ebur128                 null                    testsrc
apulsator               edgedetect              nullsink                testsrc2
arealtime               elbg                    nullsrc                 thistogram
aresample               entropy                 oscilloscope            threshold
areverse                eq                      overlay                 thumbnail
arnndn                  equalizer               owdenoise               tile
aselect                 erosion                 pad                     tinterlace
asendcmd                extractplanes           pal100bars              tlut2
asetnsamples            extrastereo             pal75bars               tmedian
asetpts                 fade                    palettegen              tmix
asetrate                fftdnoiz                paletteuse              tonemap
asettb                  fftfilt                 pan                     tonemap_vaapi
ashowinfo               field                   perms                   tpad
asidedata               fieldhint               perspective             transpose
asoftclip               fieldmatch              phase                   transpose_vaapi
asplit                  fieldorder              photosensitivity        treble
ass                     fifo                    pixdesctest             tremolo
astats                  fillborders             pixscope                trim
astreamselect           find_rect               pp                      unpremultiply
asubboost               firequalizer            pp7                     unsharp
atadenoise              flanger                 premultiply             untile
atempo                  floodfill               prewitt                 uspp
atrim                   format                  procamp_vaapi           v360
avectorscope            fps                     pseudocolor             vaguedenoiser
avgblur                 framepack               psnr                    vectorscope
axcorrelate             framerate               pullup                  vflip
bandpass                framestep               qp                      vfrdet
bandreject              freezedetect            random                  vibrance
bass                    freezeframes            readeia608              vibrato
bbox                    fspp                    readvitc                vignette
bench                   gblur                   realtime                vmafmotion
bilateral               geq                     remap                   volume
biquad                  gradfun                 removegrain             volumedetect
bitplanenoise           gradients               removelogo              vstack
blackdetect             graphmonitor            repeatfields            w3fdif
blackframe              greyedge                replaygain              waveform
blend                   haas                    reverse                 weave
bm3d                    haldclut                rgbashift               xbr
boxblur                 haldclutsrc             rgbtestsrc              xfade
bwdif                   hdcd                    roberts                 xmedian
cas                     headphone               rotate                  xstack
cellauto                hflip                   sab                     yadif
channelmap              highpass                scale                   yaepblur
channelsplit            highshelf               scale2ref               yuvtestsrc
chorus                  hilbert                 scale_vaapi             zoompan
chromahold              histeq                  scdet                   zscale
chromakey               histogram               scroll

Enabled bsfs:
aac_adtstoasc           filter_units            mjpega_dump_header      prores_metadata
av1_frame_merge         h264_metadata           mov2textsub             remove_extradata
av1_frame_split         h264_mp4toannexb        mp3_header_decompress   text2movsub
av1_metadata            h264_redundant_pps      mpeg2_metadata          trace_headers
chomp                   hapqa_extract           mpeg4_unpack_bframes    truehd_core
dca_core                hevc_metadata           noise                   vp9_metadata
dump_extradata          hevc_mp4toannexb        null                    vp9_raw_reorder
eac3_core               imx_dump_header         opus_metadata           vp9_superframe
extract_extradata       mjpeg2jpeg              pcm_rechunk             vp9_superframe_split

Enabled indevs:
alsa                    kmsgrab                 oss                     v4l2
fbdev                   lavfi                   sndio                   xcbgrab

Enabled outdevs:
alsa                    oss                     sndio                   xv
fbdev                   sdl2                    v4l2

License: nonfree and unredistributable
GEN     libavutil/libavutil.version
GEN     libswscale/libswscale.version
GEN     libswresample/libswresample.version
GEN     libpostproc/libpostproc.version
GEN     libavcodec/libavcodec.version
GEN     libavformat/libavformat.version
GEN     libavfilter/libavfilter.version
GEN     libavdevice/libavdevice.version
CC      libavdevice/alldevices.o
CC      libavdevice/alsa.o
CC      libavdevice/alsa_dec.o
CC      libavdevice/alsa_enc.o
CC      libavdevice/avdevice.o
CC      libavdevice/fbdev_common.o
CC      libavdevice/fbdev_dec.o
libavdevice/avdevice.c: In function ‘device_next’:
libavdevice/avdevice.c:88:13: warning: ‘av_oformat_next’ is deprecated [-Wdeprecated-declarations]
             if (!(prev = av_oformat_next(prev)))
             ^~
In file included from libavdevice/avdevice.h:51,
                 from libavdevice/avdevice.c:23:
./libavformat/avformat.h:2095:17: note: declared here
 AVOutputFormat *av_oformat_next(const AVOutputFormat *f);
                 ^~~~~~~~~~~~~~~
libavdevice/avdevice.c:92:13: warning: ‘av_iformat_next’ is deprecated [-Wdeprecated-declarations]
             if (!(prev = av_iformat_next(prev)))
             ^~
In file included from libavdevice/avdevice.h:51,
                 from libavdevice/avdevice.c:23:
./libavformat/avformat.h:2087:17: note: declared here
 AVInputFormat  *av_iformat_next(const AVInputFormat  *f);
                 ^~~~~~~~~~~~~~~
CC      libavdevice/fbdev_enc.o
CC      libavdevice/kmsgrab.o
CC      libavdevice/lavfi.o
CC      libavdevice/oss.o
CC      libavdevice/oss_dec.o
libavdevice/kmsgrab.c:436:16: error: ‘DRM_FORMAT_MOD_NONE’ undeclared here (not in a function); did you mean ‘DRM_FORMAT_NV12’?
       { .i64 = DRM_FORMAT_MOD_NONE }, 0, INT64_MAX, FLAGS },
                ^~~~~~~~~~~~~~~~~~~
                DRM_FORMAT_NV12
CC      libavdevice/oss_enc.o
make: *** [ffbuild/common.mak:59: libavdevice/kmsgrab.o] Error 1
make: *** Waiting for unfinished jobs....

real    28m25.383s
user    74m53.157s
sys     7m40.142s

**Comment by xbelanch** [comment]
Duplicated (https://github.com/xbelanch/OBS4Pi/issues/9#issuecomment-866686909)
