### ISSUE TITLE
errors when running build.sh

### ISSUE THREAD

**Issue by Fiskarna** [xbelanch/OBS4Pi#11]
hi. im having trouble running the build.sh script.

`23: Syntax error: "(" unexpected`

and if i remove that chunk of code, it gives me another error.

`305: time: not found`

and then it gives me the all done, but running launch_OBS.sh doesn't work.

`./launch_OBS.sh: 4: obs: not found`

for the record, i did upgrade to bullseye but it didnt update all packages. about 400 "have been kept back". could that have something to do with it? cant seem to get it to update those..

**Comment by xbelanch** [comment]
You need to finish the bullseye upgrade before you run the build.sh script. So then you must to update all the 400 packages (or 1000 in words of the author of the article [How to Upgrade Raspberry Pi OS to the Latest Version? (2021)](https://raspberrytips.com/update-raspberry-pi-latest-version/). Let me know if the syntax error persists after you finished the upgrade and thereafter reboot the system.

**Comment by Fiskarna** [comment]
hi. thank you for your quick reply. i managed to get all packages updated +rebooting yet im still having the same problem.

**Comment by xbelanch** [comment]
Can you copy/paste the whole output when you running the build.sh script? You can easy handle it if you save it first as a file:

```shell
~/OBS4Pi $ ./build.sh 2>&1 | tee output.txt
```

**Comment by Fiskarna** [comment]
dude idk why but when i ran that it just worked!! obs opened up beautifully and i'm so excited!! thank you so much 🙏

**Comment by xbelanch** [comment]
♥️
