### ISSUE TITLE
Error to install

### ISSUE THREAD

**Issue by joelemanoel** [xbelanch/OBS4Pi#13]
I have an error after try install: 

`Package: libass-dev                          NOT INSTALLED
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev : Breaks: libgcc-8-dev (< 8.4.0-2~) but 8.3.0-6+rpi1 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

real    8m27.949s
user    2m57.517s`

First step: Install Raspbian
Step Two: Upgrade by following the RaspberryPiTips tutorial
Third step: Try to install (wget https://raw.githubusercontent.com/xbelanch/OBS4Pi/main/build.sh; chmod +x build.sh; ./build.sh)

**Comment by xbelanch** [comment]
Try this: https://unix.stackexchange.com/questions/592657/full-upgrade-to-debian-testing-fails-due-to-libc6-dev-breaks-libgcc-8-dev

**Comment by joelemanoel** [comment]
![image](https://user-images.githubusercontent.com/6315310/127774815-b71bf2b4-6097-4193-a9a6-a7bda1eef1ba.jpeg)

After install OBS, OS is broken and not initialize.

**Comment by xbelanch** [comment]
Have you noticed that apt has removed a lot of packages (KDE related)?

**Comment by joelemanoel** [comment]
> Have you noticed that apt has removed a lot of packages (KDE related)?

I couldn't notice it at the time.

**Comment by xbelanch** [comment]
Do you have the script output log from the terminal?

**Comment by joelemanoel** [comment]
> Do you have the script output log from the terminal?

Build is correctly, but after install Chromium end other functions dont work, after this i am reboot Rasp and OS is broken.

**Comment by xbelanch** [comment]
Maybe this reddit can fix that issue: https://www.reddit.com/r/voidlinux/comments/jdk9zw/no_session_for_pid_xxx_everytime_i_login_lxde/

**Comment by joelemanoel** [comment]
> Maybe this reddit can fix that issue: https://www.reddit.com/r/voidlinux/comments/jdk9zw/no_session_for_pid_xxx_everytime_i_login_lxde/

I cannot open the terminal.

**Comment by xbelanch** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=109429

>Most Linux setups will switch from X to a command line by pressing one of the CTRL-ALT-F2 to CTRL-ALT-F6 combinations. You get back to X by ALT-F7. (The X didn't exit.)

**Comment by joelemanoel** [comment]
> https://www.raspberrypi.org/forums/viewtopic.php?t=109429
> 
> > Most Linux setups will switch from X to a command line by pressing one of the CTRL-ALT-F2 to CTRL-ALT-F6 combinations. You get back to X by ALT-F7. (The X didn't exit.)

I'm reinstalling everything, let's try again, but I believe it gives the same problem xD
Return soon with new information.

Thanks for you help @xbelanch

**Comment by xbelanch** [comment]
>I'm reinstalling everything, let's try again, but I believe it gives the same problem xD

Hope you don't!

**Comment by joelemanoel** [comment]
OS Broken after install "gcc-8-base"

**Comment by joelemanoel** [comment]
@xbelanch You recommend "Raspberry Pi OS" or "Raspberry Pi OS Full" to install?

**Comment by xbelanch** [comment]
Follow this tutorial: https://doc.akito.ooo/books/essentials/page/manually-upgrade-debian-from-buster-to-bullseye

Sent from ProtonMail for iOS

Actiu dl, ag 2, 2021 a 00:28, joelemanoel ***@***.***> va escriure:

**Comment by xbelanch** [comment]
> @xbelanch You recommend "Raspberry Pi OS" or "Raspberry Pi OS Full" to install?

IMO I prefer a basic OS installation and then install a light desktop like i3wm but actually you should upgrade the os system to bullseye without no issue to any installation flavours of Pi OS. The main problem as you found is the libc6-dev unmet dependencies after upgrade the system (without reboot!). In that scenario I found very useful all the options explained on the trouble shooting section of that guide: https://doc.akito.ooo/books/essentials/page/manually-upgrade-debian-from-buster-to-bullseye

**Comment by xbelanch** [comment]
Close issue after a time of no more interaction or feedback
