### ISSUE TITLE
meson.build:1:0 ERROR: Meson version is 0.56.2 but project requires >=0.59.0

### ISSUE THREAD

**Issue by sydesb** [xbelanch/OBS4Pi#18]
Hi,
Thank you for your script !

There is a problem with pipewire

Get and build Pipewire : 
.....
meson.build:1:0 ERROR: Meson version is 0.56.2 but project requires >=0.59.0

**Comment by eli-schwartz** [comment]
Meson is telling you that this project requires a newer version than the one you have installed. This is not a bug in the project.

You will need to upgrade Meson itself, or use a newer version of a Linux distro that has upgraded the distro packaged version of Meson.

**Comment by sydesb** [comment]
I understand but it's the last version of Raspberry PI OS and when i update Meson, the last version is 0.56.2
How could I update with 0.59 ?

**Comment by eli-schwartz** [comment]
> I understand but it's the last version of Raspberry PI OS and when i update Meson, the last version is 0.56.2

That's probably not the fault of this project, but you do have options. For example, you could install https://archlinuxarm.org/

Alternatively, you could follow the instructions at https://mesonbuild.com/Getting-meson.html

**Comment by sydesb** [comment]
It's what I told :
sudo pip3 install meson  -> 0.56.2

I'll try archlinuxARM
