### ISSUE TITLE
error: obs: symbol lookup error: obs: undefined symbol: obs_set_nix_platform

### ISSUE THREAD

**Issue by lblabr** [xbelanch/OBS4Pi#19]
build were correct on RPI4, bullseye, after starting obs, the error:

obs: symbol lookup error: obs: undefined symbol: obs_set_nix_platform

accours. do you have a hint ?

**Comment by xbelanch** [comment]
Maybe this thread could be helpful to fix it? https://obsproject.com/forum/threads/obs-error-undefined-symbold-with-debian-based-build-directions.96598/ or https://obsproject.com/forum/threads/local-obs-build-wont-start-reports-undefined-symbol-obs_set_ui_task_handler.138934/ Although it's not raspi related perhaps you've previously installed obs package before you compile it?

**Comment by xbelanch** [comment]
Closed by inactive
