### ISSUE TITLE
obs-ffmpeg compilation error

### ISSUE THREAD

**Issue by xbelanch** [xbelanch/OBS4Pi#7]

**Comment by carlosnewmusic** [comment]
`-- Found XCB: /usr/lib/arm-linux-gnueabihf/libxcb.so;/usr/lib/arm-linux-gnueabihf/libxcb-randr.so;/usr/lib/arm-linux-gnueabihf/libxcb-shm.so;/usr/lib/arm-linux-gnueabihf/libxcb-xfixes.so;/usr/lib/arm-linux-gnueabihf/libxcb-xinerama.so  found components:  XCB RANDR SHM XFIXES XINERAMA 
CMake Error at plugins/linux-capture/CMakeLists.txt:53 (message):
  PipeWire library not found! Please install PipeWire or set
  ENABLE_PIPEWIRE=OFF


-- Configuring incomplete, errors occurred!
See also "/tmp/tmp.8hCLgmTl3x/FFmpeg/obs-studio/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/tmp.8hCLgmTl3x/FFmpeg/obs-studio/build/CMakeFiles/CMakeError.log".
-----------------------------------
             Building
-----------------------------------
make: *** No se especificó ningún objetivo y no se encontró ningún makefile.  Alto.
make: *** No hay ninguna regla para construir el objetivo 'install'.  Alto.

All done..........!
Remember you need MESA_GL_VERSION_OVERRIDE=3.3 obs to start OBS!
If you get an opengl seg fault try to fix it with
export LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libGL.so
before launch OBS

Read the README.md for more information
`

**Comment by xbelanch** [comment]
Please, check the new update to verify that OBS can successfully compile with no errors
